API_KEY = ''
API_SECRET = ''

DATE_FORMAT = "%b %d, %Y"
TIME_FORMAT = "%H:%M"

MAX_CONCURRENCY_BINANCE_TASK = 10
MAX_CONCURRENCY_GOOGLE_SHEET_TASK = 10

UPDATE_INTERVAL = 60  # seconds

CREDS_PATH = 'creds.json'

DOCUMENT_NAME = 'test'

SHARE_TO_EMAIL = ''
